### ISSUE TITLE
fs_app.beam failed: :badfile

### ISSUE THREAD

**Issue by quolpr** [synrc/fs#56]
I am getting such error om application start:

```
[error] Loading of /Users/.../_build/dev/lib/fs/ebin/fs_app.beam failed: :badfile

[error] beam/beam_load.c(1189): Error loading module fs_app:
  mandatory chunk of type 'Atom' not found

[error] an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:fs, {:bad_return, {{:fs_app, :start, [:normal, []]}, {:EXIT, {:undef, [{:fs_app, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 273]}]}}}}}}
        (phoenix_live_reload) lib/phoenix_live_reload/channel.ex:10: Phoenix.LiveReload.Channel.join/3
        (phoenix) lib/phoenix/channel/server.ex:169: Phoenix.Channel.Server.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

Tool versions:

```
erlang 18.3
elixir 1.3.1
```

Mac OS:

```
    System Software Overview:

      System Version: macOS 10.12.6 (16G1114)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
```

Is there any idea what is happening?

**Comment by quolpr** [comment]
And ond path
> /Users/.../_build/dev/lib/fs/ebin/fs_app.beam

I can see the beam file and it is ok

**Comment by 5HT** [comment]
> mandatory chunk of type 'Atom' not found

Try to switch Erlang releases, this is due wrong byte-code for actual Virtual Machine.

Therefore you may close this issue, because we do not provide BEAM files in any installation.

**Comment by quolpr** [comment]
Ok, I found the problem. I was needed to delete deps dir(it was compiled for another version of erlang). Thank you for a quick answer!
